export const FETCH_USERS = 'user/FETCH_USERS'
export const FETCH_USER = 'user/FETCH_USER'
export const DELETE_USER = 'user/DELETE_USER'
export const UPDATE_USER = 'user/UPDATE_USER'
export const SESSION_SIGNIN = 'user/SIGNIN'
export const SESSION_SIGNOUT = 'user/SIGNOUT'
export const REFRESH_TOKEN = 'user/REFRESH_TOKEN'
export const MUTATE_HAS_UNREAD_NOTIFICATION = 'user/MUTATE_HAS_UNREAD_NOTIFICATION'
