export const FETCH_PROJECTS = 'project/FETCH_PROJECTS'
export const FETCH_PROJECT = 'project/FETCH_PROJECT'
export const CREATE_PROJECT = 'project/CREATE_PROJECT'
export const DELETE_PROJECT = 'project/DELETE_PROJECT'
export const UPDATE_PROJECT = 'project/UPDATE_PROJECT'
